version: '3.1'
services:
  herd-service:
    container_name: herd-service
    image: herd-service
    build: ./
    ports:
      - 8090:8090
    depends_on:
      - postgresqldb
      - redis
  postgresqldb:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=halterdb
  redis:
    image: redis:latest
    ports:
      - 6379:6379